version: "3"
services:
  dbserver:
    image: postgres:12
    container_name: herokuconnectdb
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: herokuconn
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
